### ISSUE TITLE
您好，视频链接能分享下吗？多谢

### ISSUE THREAD

**Issue by zhoudaqing** [thought7878/chanlun_notes#1]
朋友您好，请问文章中的视频能分享下吗？多谢了

https://github.com/thought7878/chanlun_notes/blob/master/17.%E6%95%99%E4%BD%A0%E7%82%92%E8%82%A1%E7%A5%A817%EF%BC%9A%E8%B5%B0%E5%8A%BF%E7%BB%88%E5%AE%8C%E7%BE%8E/%E6%95%99%E4%BD%A0%E7%82%92%E8%82%A1%E7%A5%A817%EF%BC%9A%E8%B5%B0%E5%8A%BF%E7%BB%88%E5%AE%8C%E7%BE%8E.md

**Comment by thought7878** [comment]
优酷有，搜索就能找到

**Comment by thought7878** [comment]
> 朋友您好，请问文章中的视频能分享下吗？多谢了
> 
> https://github.com/thought7878/chanlun_notes/blob/master/17.%E6%95%99%E4%BD%A0%E7%82%92%E8%82%A1%E7%A5%A817%EF%BC%9A%E8%B5%B0%E5%8A%BF%E7%BB%88%E5%AE%8C%E7%BE%8E/%E6%95%99%E4%BD%A0%E7%82%92%E8%82%A1%E7%A5%A817%EF%BC%9A%E8%B5%B0%E5%8A%BF%E7%BB%88%E5%AE%8C%E7%BE%8E.md

优酷有，搜索就能找到
